# Generated by Django 6.0.7 on 2026-08-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ksldc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escom_name', models.CharField(max_length=100)),
                ('bio_mass', models.PositiveIntegerField(default=0)),
                ('cogen', models.PositiveIntegerField(default=0)),
                ('mini_hydro', models.PositiveIntegerField(default=0)),
                ('wind', models.PositiveIntegerField(default=0)),
                ('solar', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ksldc_data',
            },
        ),
    ]
