# Generated by Django 6.0.7 on 2026-09-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_created_at_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksldc',
            name='time_block',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ksldc',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
