# Generated by Django 6.0.7 on 2026-09-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_ksldc_time_block_alter_ksldc_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ksldc',
            name='time',
        ),
        migrations.AddField(
            model_name='ksldc',
            name='date_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ksldc',
            name='updated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ksldc',
            name='time_block',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
