# Generated by Django 6.0.7 on 2026-09-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_ksldc_time_ksldc_date_time_ksldc_updated_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksldc',
            name='bio_mass',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ksldc',
            name='cogen',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ksldc',
            name='mini_hydro',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ksldc',
            name='solar',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ksldc',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ksldc',
            name='wind',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
