# Generated by Django 6.0.7 on 2026-09-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_ksldc_bio_mass_alter_ksldc_cogen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ksldc',
            name='time_block',
        ),
        migrations.AlterField(
            model_name='ksldc',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
