# Generated by Django 6.0.7 on 2026-09-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_ksldc_time_block_alter_ksldc_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksldc',
            name='date_time',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='ksldc',
            name='updated_time',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
